"use server";

import { createClient } from "@/utils/supabase/server";
import { geminiModel } from "@/lib/gemini";
import { revalidatePath } from "next/cache";

/**
 * Admin: Generate quiz content using Gemini AI (Preview only)
 */
export async function generateQuizAI(params: {
    topic: string;
    difficulty: string;
    num_questions: number;
}) {
    const supabase = await createClient();

    // 1. Verify Admin Role
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return { error: "Authentication required" };

    const { data: profile } = await supabase
        .from("profiles")
        .select("role")
        .eq("id", user.id)
        .single();

    if (profile?.role !== 'admin') return { error: "Admin access required" };

    // 2. Deep Prompting for Structured Quiz
    const prompt = `Generate a high-quality quiz about "${params.topic}" at "${params.difficulty}" difficulty.
    Generate exactly ${params.num_questions} questions.
    
    Output ONLY a JSON array of objects with this structure:
    [
      {
        "question": "string",
        "options": ["string", "string", "string", "string"],
        "correct_index": number (0-3),
        "timer_seconds": 15
      }
    ]`;

    try {
        const result = await geminiModel.generateContent(prompt);
        const responseText = result.response.text();
        const quizQuestions = JSON.parse(responseText);

        if (!Array.isArray(quizQuestions)) {
            throw new Error("AI returned invalid data format");
        }

        // Return the content for editing in the UI
        return {
            success: true,
            data: {
                title: `${params.topic.toUpperCase()} TRIAL`,
                description: `A competitive trial generated by AEGIS AI focusing on ${params.topic}. Level: ${params.difficulty}`,
                questions: quizQuestions.map((q: any) => ({
                    questionText: q.question,
                    options: q.options,
                    correctIndex: q.correct_index,
                    timerSeconds: q.timer_seconds || 15
                }))
            }
        };

    } catch (err: any) {
        console.error("Gemini Quiz Generation Failed:", err);
        return { error: "Failed to generate quiz. Please check topic or try again." };
    }
}
